apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            # 规则: 节点的标签 "traefik-exclude" 不等于 "true"
            - key: traefik-exclude
              operator: NotIn
              values:
              - "true"
