apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    # 这里是 Traefik 的自定义配置
    additionalArguments:
      # 添加证书解析器，用于自动申请 Let's Encrypt 证书
      - "--certificatesresolvers.default.acme.email=hewenjin94@outlook.com"  # 替换为你的邮箱
      - "--certificatesresolvers.default.acme.storage=/data/acme.json"
      - "--certificatesresolvers.default.acme.httpchallenge.entrypoint=web"  # 使用 HTTP-01 验证
    ports:
      web:
        exposedPort: 8000   # 确保 HTTP (80) 端口是开放的，用于验证
      websecure:
        exposedPort: 8443   # 确保 HTTPS (443) 端口是开放的，用于服务访问
# apiVersion: helm.cattle.io/v1
# kind: HelmChartConfig
# metadata:
#   name: traefik
#   namespace: kube-system
# spec:
#   valuesContent: |
#     service:
#       annotations:
#         svccontroller.k3s.cattle.io/lbpool: "traefik"
