# This module provides basic home manager desktop environment services and applications
{
  inputs,
  pkgs,
  lib,
  mainMonitor,
  config,
  me,
  ...
}:
{
  imports = [
    inputs.dms.homeModules.niri
    inputs.dms.homeModules.dank-material-shell
    inputs.dms-plugin-registry.modules.default
  ];

  services = {
    easyeffects.enable = true;
    # udisks2 GUI front end
    udiskie.enable = true;
  };
  home.sessionVariables = {
    DMS_SCREENSHOT_EDITOR = "swappy";
  };
  programs = {
    dank-material-shell = {
      enable = true;
      niri.enableKeybinds = false;
      niri.includes = {
        enable = true; # Enable config includes hack. Enabled by default.
        override = true; # If disabled, DMS settings won't be prioritized over settings defined using niri-flake
        originalFileName = "dms"; # A new name (without extension) for the config file generated by niri-flake.
        filesToInclude = [
          # Files under `$XDG_CONFIG_HOME/niri/dms` to be included into the new config
          "alttab" # Please note that niri will throw an error if any of these files are missing.
          "binds"
          "colors"
          "layout"
          "outputs"
          "wpblur"
          "cursor"
          "windowrules"
        ];
      };
      systemd = {
        enable = true; # Systemd service for auto-start
        restartIfChanged = true; # Auto-restart dms.service when dank-material-shell changes
      };
      # Core features
      enableSystemMonitoring = true; # System monitoring widgets (dgop)
      enableVPN = true; # VPN management widget
      enableDynamicTheming = true; # Wallpaper-based theming (matugen)
      enableAudioWavelength = true; # Audio visualizer (cava)
      enableCalendarEvents = true; # Calendar integration (khal)
      enableClipboardPaste = true; # Pasting items from the clipboard (wtype)
      settings = builtins.fromJSON (builtins.readFile ../../xdg/config/DankMaterialShell/settings.json);
      clipboardSettings = builtins.fromJSON (
        builtins.readFile ../../xdg/config/DankMaterialShell/clsettings.json
      );

      plugins = {
        dankBatteryAlerts.enable = true;
        dankKDEConnect.enable = true;
        dankPomodoroTimer.enable = true;
        dankLauncherKeys.enable = true;
        musicLyrics.enable = true;
        displayManager.enable = true;
        dankAudioVisualizer.enable = true;
        dankClight.enable = true;
        dankActions.enable = true;
        dankHooks.enable = true;
        dankStickerSearch.enable = true;
        emojiLauncher.enable = true;
        audioInhibit.enable = true;
        easyEffects.enable = true;
        wallpaperBing = {
          enable = true;
          settings = {
            enableDailyRefresh = true;
            GnomeExtensionBingWallpaperCompatibility = true;
            deleteOld = false;
          };
        };
      };
    };
    # vim like image viewer
    imv.enable = true;
    # vim like pdf viewer
    zathura = {
      enable = true;
      options = {
        recolor = true;
      };
    };
    # firefox with some native host messaging apps
    firefox = {
      enable = true;
      profiles = {
        "${me.username}" = {
          id = 0;
          extensions.force = true;
        };
      };
      nativeMessagingHosts = with pkgs; [
        pywalfox-native
        # Tridactyl native connector
        tridactyl-native
      ];
    };
  };

  home.packages = with pkgs; [
    kdePackages.qt6ct
    ddcutil
    imagemagick
    slurp
    tesseract
    dsearch
    pavucontrol
    swappy
    brightnessctl
    playerctl
    pulseaudio
    gnupg
    xrdb
    file-roller
    baobab
    nautilus
    nautilus-python
    gnome-calculator
    gnome-clocks
    gnome-software # for flatpak
    # vdhcoapp # for videodownloadhelper, the browser extension. for first time setup, run `vdhcoapp install`
  ];
  xdg = {
    # disable nm-applet autostart
    configFile."autostart/nm-applet.desktop".text = ''
      [Desktop Entry]
      Type=Application
      Name=Network Manager Applet
      Exec=nm-applet
      Hidden=true
    '';
    # customize nautilus right click menu
    dataFile."nautilus-python/extensions/image_tools_extension.py".source =
      ../../xdg/data/nautilus-python/extensions/image_tools_extension.py;
  };
}
