# This module provides basic home manager desktop environment services and applications
{
  inputs,
  outputs,
  pkgs,
  lib,
  mainMonitor,
  config,
  me,
  ...
}:
{
  imports = [
    inputs.dms.homeModules.niri
    inputs.dms.homeModules.dank-material-shell
    inputs.dms-plugin-registry.modules.default
    inputs.danksearch.homeModules.default
    outputs.homeManagerModules.niri
  ];

  services = {
    pass-secret-service.enable = true;
    easyeffects.enable = true;
    # udisks2 GUI front end
    udiskie.enable = true;
  };
  home.sessionVariables = {
    DMS_SCREENSHOT_EDITOR = "swappy";
  };
  programs = {
    dank-material-shell = {
      enable = true;
      niri.enableKeybinds = false;
      niri.includes = {
        enable = true; # Enable config includes hack. Enabled by default.
        override = true; # If disabled, DMS settings won't be prioritized over settings defined using niri-flake
        originalFileName = "dms"; # A new name (without extension) for the config file generated by niri-flake.
        filesToInclude = [
          # Files under `$XDG_CONFIG_HOME/niri/dms` to be included into the new config
          "alttab" # Please note that niri will throw an error if any of these files are missing.
          "binds"
          "colors"
          "layout"
          "outputs"
          "wpblur"
          "cursor"
          "windowrules"
        ];
      };
      systemd = {
        enable = true; # Systemd service for auto-start
        restartIfChanged = true; # Auto-restart dms.service when dank-material-shell changes
      };
      # Core features
      enableSystemMonitoring = true; # System monitoring widgets (dgop)
      enableVPN = true; # VPN management widget
      enableDynamicTheming = true; # Wallpaper-based theming (matugen)
      enableAudioWavelength = true; # Audio visualizer (cava)
      enableCalendarEvents = true; # Calendar integration (khal)
      enableClipboardPaste = true; # Pasting items from the clipboard (wtype)
      settings = builtins.fromJSON (builtins.readFile ../../xdg/config/DankMaterialShell/settings.json);
      clipboardSettings = builtins.fromJSON (
        builtins.readFile ../../xdg/config/DankMaterialShell/clsettings.json
      );

      plugins = {
        dankBatteryAlerts.enable = true;
        dankKDEConnect.enable = true;
        dankPomodoroTimer.enable = true;
        dankLauncherKeys.enable = true;
        musicLyrics.enable = true;
        dankActions.enable = true;
        dankHooks.enable = true;
        dankStickerSearch.enable = true;
        emojiLauncher.enable = true;
        easyEffects.enable = true;
        calculator.enable = true;
        sshConnections.enable = true;
        dankGifSearch.enable = true;
        commandRunner = {
          enable = true;
          settings = {
            terminal = "ghostty";
          };
        };
        webSearch = {
          enable = true;
          settings = {
            defaultEngine = "duckduckgo";
          };
        };
        wallpaperBing = {
          enable = true;
          settings = {
            enableDailyRefresh = true;
            GnomeExtensionBingWallpaperCompatibility = true;
            deleteOld = false;
          };
        };
      };
    };
    dsearch = {
      enable = true;

      # Custom configuration (TOML format)
      config = {
        # Server configuration
        listen_addr = ":43654";

        # Index settings
        index_path = "${config.home.homeDirectory}/.cache/danksearch/index";
        max_file_bytes = 2097152; # 2MB
        worker_count = 4;
        index_all_files = true;

        # Auto-reindex settings
        auto_reindex = false;
        reindex_interval_hours = 24;

        index = {
          paths = [
            "${config.home.homeDirectory}/Desktop"
            "${config.home.homeDirectory}/Documents"
            "${config.home.homeDirectory}/Downloads"
            "${config.home.homeDirectory}/Music"
            "${config.home.homeDirectory}/Pictures"
            "${config.home.homeDirectory}/Public"
            "${config.home.homeDirectory}/Videos"
            "${config.home.homeDirectory}/Templates"
          ];
          max_depth = 5;
          exclude_hidden = true;
        };
        # Index paths configuration
        index_paths = [
          {
            path = "${config.home.homeDirectory}/Rclone";
            max_depth = 5;
            watch = false;
          }
        ];
      };
    };
    # vim like image viewer
    imv.enable = true;
    # vim like pdf viewer
    zathura = {
      enable = true;
      options = {
        selection-clipboard = "clipboard";
        recolor = true;
      };
    };
    # firefox with some native host messaging apps
    firefox = {
      enable = true;
      profiles = {
        "${me.username}" = {
          id = 0;
          extensions.force = true;
        };
      };
      nativeMessagingHosts = with pkgs; [
        ff2mpv
        pywalfox-native
        # Tridactyl native connector
        tridactyl-native
      ];
    };
  };

  home.packages = with pkgs; [
    ff2mpv
    yt-dlp
    kdePackages.qt6ct
    libsForQt5.qt5ct
    imagemagick
    slurp
    tesseract
    pavucontrol
    swappy
    brightnessctl
    playerctl
    pulseaudio
    gnupg
    xrdb
    file-roller
    baobab
    nautilus
    spotify
    nautilus-python
    gnome-calculator
    gnome-clocks
    gnome-software # for flatpak
    # vdhcoapp # for videodownloadhelper, the browser extension. for first time setup, run `vdhcoapp install`
  ];
  xdg = {
    # disable nm-applet autostart
    configFile."autostart/nm-applet.desktop".text = ''
      [Desktop Entry]
      Type=Application
      Name=Network Manager Applet
      Exec=nm-applet
      Hidden=true
    '';
    # customize nautilus right click menu
    dataFile."nautilus-python/extensions/image_tools_extension.py".source =
      ../../xdg/data/nautilus-python/extensions/image_tools_extension.py;
  };
}
